const icons={plus:'<path d="M12 5v14M5 12h14"/>',chat:'<path d="M21 11.5a8.5 8.5 0 0 1-8.5 8.5H4l-1 1V11.5a8.5 8.5 0 0 1 17 0Z"/><path d="M7 9h9M7 13h6"/>',grid:'<rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/>',book:'<path d="M12 5C8 2 4 3 3 4v15c3-1 6-1 9 1 3-2 6-2 9-1V4c-3-1-6-1-9 1Zm0 0v15"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',spark:'<path d="m12 3 2.4 6.6L21 12l-6.6 2.4L12 21l-2.4-6.6L3 12l6.6-2.4L12 3ZM20 2v4M18 4h4"/>',menu:'<path d="M4 6h16M4 12h16M4 18h16"/>',info:'<circle cx="12" cy="12" r="9"/><path d="M12 11v6M12 7h.01"/>',chevron:'<path d="m7 10 5 5 5-5"/>',wrench:'<path d="M14 6a5 5 0 0 0-6 6L3 17a2.8 2.8 0 0 0 4 4l5-5a5 5 0 0 0 6-6l-3 3-4-4 3-3Z"/>',clipboard:'<rect x="5" y="4" width="14" height="17" rx="2"/><rect x="9" y="2" width="6" height="4" rx="1"/><path d="m8 12 2 2 5-5M8 17h7"/>',layers:'<path d="m12 3 10 5-10 5L2 8l10-5ZM2 12l10 5 10-5M2 16l10 5 10-5"/>',arrowUp:'<path d="M12 19V5m-6 6 6-6 6 6"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>',copy:'<rect x="8" y="8" width="12" height="13" rx="2"/><path d="M16 8V3H3v13h5"/>',like:'<path d="M7 10v11H3V10h4Zm0 0 5-8c3 0 2 5 1 7h6c2 0 2 2 1 5l-2 7H7"/>',file:'<path d="M14 2H5v20h14V7l-5-5Zm0 0v6h5M8 12h8M8 16h6"/>'};
const svg=n=>`<svg viewBox="0 0 24 24" aria-hidden="true">${icons[n]||icons.spark}</svg>`;
const $=id=>document.getElementById(id);const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
document.querySelectorAll('[data-icon]').forEach(e=>e.innerHTML=svg(e.dataset.icon));
const serviceUrl='https://chuangan-ruikong-ai-demo.z911720037.chatgpt.site/';
const isEntry=location.hostname.endsWith('github.io');
let docs=[],sessions=[],active=null,busy=false,showSources=true;
const current=()=>sessions.find(s=>s.id===active);
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),3000)}
function modal(title,html){$('modal-title').textContent=title;$('modal-content').innerHTML=html;if(!$('modal').open)$('modal').showModal()}
function view(name){document.querySelectorAll('.view').forEach(e=>e.hidden=e.id!==name+'-view');document.querySelectorAll('[data-view]').forEach(e=>e.classList.toggle('active',e.dataset.view===name));$('page-name').textContent={chat:'AI 工作台',knowledge:'知识库'}[name];$('sidebar').classList.remove('open')}
function entryLink(q=''){const u=new URL(serviceUrl);if(q)u.hash=new URLSearchParams({question:q,model:$('product-model').value}).toString();return u.href}
function openEntry(q=''){modal('进入真实知识问答',`<p>真实问答运行在独立服务中，根据产品手册检索结果生成回答。当前服务保留登录访问。</p><a class="service-link" href="${esc(entryLink(q))}" target="_blank" rel="noopener">打开知识库，登录后提问 ↗</a><p>此页面是 GitHub Pages 入口，不会生成预设答案。</p>`)}
function render(){const s=current();$('welcome').hidden=!!s?.messages.length;$('messages').innerHTML=(s?.messages||[]).map((m,i)=>m.role==='user'?`<article class="message user"><div class="user-bubble">${esc(m.text)}</div></article>`:`<article class="message assistant"><div class="assistant-heading"><span class="mini-mark">睿</span>睿控知识助手 <span class="demo-badge">手册问答</span></div><div class="answer"><p class="answer-text">${esc(m.error||m.result.answer.replace(/\[((?:CA100|CA700|600U|CL100|CL200))-p(\d{3})-\d{2}\]/g,(_,model,page)=>'['+model+' PDF第'+Number(page)+'页]'))}</p>${showSources&&m.result?.sources?.length?`<div class="sources">${m.result.sources.map((c,j)=>`<button class="source" data-source="${i}:${j}">${esc(c.model)} · PDF 第 ${c.page} 页 ↗</button>`).join('')}</div>`:''}<div class="message-actions"><button data-copy="${i}">${svg('copy')}复制</button></div></div></article>`).join('');$('history').innerHTML=sessions.map(s=>`<button data-session="${s.id}" class="${s.id===active?'active':''}">${esc(s.title)}</button>`).join('')||'<div class="history-empty">开始一次对话，<br>让问题有迹可循。</div>';$('conversation').scrollTop=$('conversation').scrollHeight}
function newChat(){if(busy)return toast('请等待当前回答完成');active=null;$('prompt').value='';$('send').disabled=true;view('chat');render()}
async function request(path,options){const r=await fetch(path,options);let body;try{body=await r.json()}catch{throw new Error('服务暂不可用，请重新登录后重试')}if(!r.ok)throw new Error(body.error||'请求失败');return body}
let embedder;
async function embedLocal(question){
 const {pipeline,env}=await import('https://cdn.jsdelivr.net/npm/@huggingface/transformers@4.3.0');
 env.allowLocalModels=false;env.backends.onnx.wasm.numThreads=1;
 embedder??=pipeline('feature-extraction','Xenova/paraphrase-multilingual-MiniLM-L12-v2',{dtype:'q8',revision:'2c4055b12046f11709e9df2c122e59ffbdc2f900',progress_callback:p=>{if(p.status==='progress'&&p.progress)document.querySelector('#messages .pending-answer')?.replaceChildren(document.createTextNode('正在下载本地检索模型：'+Math.round(p.progress)+'%（首次使用较慢）'));}});
 try{const named=[...new Set(question.toUpperCase().match(/(?:CA|CL)\d{2,4}|600U/g)||[])];const prefix=named.length?named.join(' '):$('product-model').value==='auto'?'':$('product-model').value;const out=await(await embedder)(prefix+' '+question,{pooling:'mean',normalize:true,truncation:true,max_length:512});return Array.from(out.data)}catch(e){console.error('Local embedding failed',String(e));embedder=null;throw new Error('本地检索模型加载失败，请检查网络后重试')}
}
async function send(text){const q=(text??$('prompt').value).trim();if(!q||busy)return;if(q.length>1500)return toast('问题请控制在 1500 字以内');if(isEntry)return openEntry(q);busy=true;view('chat');$('send').disabled=true;if(!active){active=String(Date.now());sessions.unshift({id:active,title:q,messages:[]})}const s=current();s.messages.push({role:'user',text:q});$('prompt').value='';render();const pending=document.createElement('div');pending.className='answer pending-answer';pending.textContent='正在检索手册并生成回答…';$('messages').append(pending);try{const queryVector=await embedLocal(q);pending.textContent='正在检索手册并生成回答…';const result=await request('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:q,model:$('product-model').value,queryVector})});s.messages.push({role:'assistant',result})}catch(e){s.messages.push({role:'assistant',error:e.message.replace(/DeepSeek/gi,'问答')+'。未生成模拟回答。'});$('prompt').value=q}finally{busy=false;render();$('send').disabled=!$('prompt').value.trim()}}
async function openDoc(model){if(isEntry)return openEntry();try{const data=await request('/api/document?model='+encodeURIComponent(model));modal(data.document.filename,data.excerpts.map(c=>`<h3>PDF 第 ${c.page} 页</h3><pre class="source-text">${esc(c.text)}</pre>`).join(''))}catch(e){toast(e.message)}}
document.addEventListener('click',async e=>{const t=e.target.closest('button');if(!t)return;if(t.dataset.view)view(t.dataset.view);if(t.dataset.prompt)send(t.dataset.prompt);if(t.dataset.doc)openDoc(t.dataset.doc);if(t.dataset.session&&!busy){active=t.dataset.session;view('chat');render()}if(t.dataset.source){const [i,j]=t.dataset.source.split(':').map(Number);const c=current().messages[i].result.sources[j];modal(c.title,`<p>${esc(c.model)} · PDF 第 ${c.page} 页 · ${esc(c.section||'原文摘录')}</p><pre class="source-text">${esc(c.text)}</pre>`)}if(t.dataset.copy){const m=current().messages[Number(t.dataset.copy)];try{await navigator.clipboard.writeText(m.result?.answer||m.error);toast('回答已复制')}catch{toast('请选中回答文字复制')}}});
$('send').onclick=()=>send();$('prompt').oninput=()=>$('send').disabled=busy||!$('prompt').value.trim();$('prompt').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();send()}};$('new-chat').onclick=()=>newChat();document.querySelector('.brand').onclick=e=>{e.preventDefault();newChat()};$('menu').onclick=()=>$('sidebar').classList.toggle('open');$('close-modal').onclick=()=>$('modal').close();$('knowledge-toggle').onclick=()=>{showSources=!showSources;$('knowledge-toggle').classList.toggle('selected',showSources);$('knowledge-toggle').setAttribute('aria-pressed',String(showSources));render()};$('info').onclick=()=>modal('关于知识问答','<p>检索依据：公司提供的 5 份产品手册。回答附原文和 PDF 页码；找不到依据时会说明，型号或部件不明确时会追问。</p><p>当前问题独立检索。追问请带上型号和问题条件；对话仅保留在当前页面，刷新后清空。</p>');
async function init(){if(isEntry){document.querySelector('.demo-badge').textContent='GitHub · 访问入口';document.querySelector('.composer-caption').textContent='点击发送可进入真实知识库服务；此页面不生成模拟回答。';$('document-list').innerHTML='<p>已整理 CA100、CA700、600U、CL100、CL200 五份手册。进入知识库后可查看引用原文。</p><a class="service-link" href="'+serviceUrl+'" target="_blank" rel="noopener">进入知识库 ↗</a>';return}try{const c=await request('/api/catalog');docs=c.documents;document.querySelector('.count-pill').textContent=docs.length+' 份';document.querySelector('.library-bar > span').textContent=c.pages+' 页 · '+c.chunks+' 个检索片段';$('document-list').innerHTML=docs.map(d=>`<button class="document-row" data-doc="${esc(d.model)}"><span class="doc-icon">${svg('file')}</span><span><strong>${esc(d.filename)}</strong><small>${d.model} · ${d.pages} 页</small></span><span class="doc-arrow">↗</span></button>`).join('');if(!c.ready)toast('模型服务尚未配置，当前无法生成回答')}catch(e){toast(e.message)}const params=new URLSearchParams(location.hash.slice(1));if(params.has('question')){$('prompt').value=params.get('question').slice(0,1500);if([...$('product-model').options].some(o=>o.value===params.get('model')))$('product-model').value=params.get('model');$('send').disabled=false;history.replaceState(null,'',location.pathname)}}init();
