const icons={plus:'<path d="M12 5v14M5 12h14"/>',chat:'<path d="M21 11.5a8.5 8.5 0 0 1-8.5 8.5H4l-1 1V11.5a8.5 8.5 0 0 1 17 0Z"/><path d="M7 9h9M7 13h6"/>',grid:'<rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/>',book:'<path d="M12 5C8 2 4 3 3 4v15c3-1 6-1 9 1 3-2 6-2 9-1V4c-3-1-6-1-9 1Zm0 0v15"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',spark:'<path d="m12 3 2.4 6.6L21 12l-6.6 2.4L12 21l-2.4-6.6L3 12l6.6-2.4L12 3ZM20 2v4M18 4h4"/>',menu:'<path d="M4 6h16M4 12h16M4 18h16"/>',info:'<circle cx="12" cy="12" r="9"/><path d="M12 11v6M12 7h.01"/>',chevron:'<path d="m7 10 5 5 5-5"/>',wrench:'<path d="M14 6a5 5 0 0 0-6 6L3 17a2.8 2.8 0 0 0 4 4l5-5a5 5 0 0 0 6-6l-3 3-4-4 3-3Z"/>',clipboard:'<rect x="5" y="4" width="14" height="17" rx="2"/><rect x="9" y="2" width="6" height="4" rx="1"/><path d="m8 12 2 2 5-5M8 17h7"/>',layers:'<path d="m12 3 10 5-10 5L2 8l10-5ZM2 12l10 5 10-5M2 16l10 5 10-5"/>',arrowUp:'<path d="M12 19V5m-6 6 6-6 6 6"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>',copy:'<rect x="8" y="8" width="12" height="13" rx="2"/><path d="M16 8V3H3v13h5"/>',like:'<path d="M7 10v11H3V10h4Zm0 0 5-8c3 0 2 5 1 7h6c2 0 2 2 1 5l-2 7H7"/>',file:'<path d="M14 2H5v20h14V7l-5-5Zm0 0v6h5M8 12h8M8 16h6"/>'};
const svg=n=>`<svg viewBox="0 0 24 24" aria-hidden="true">${icons[n]||icons.spark}</svg>`;
const $=id=>document.getElementById(id);const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
document.querySelectorAll('[data-icon]').forEach(e=>e.innerHTML=svg(e.dataset.icon));
const experts=[{id:'general',name:'睿控综合助手',desc:'从日常问答到工作整理，帮助你把需求说清楚、把下一步理明白。',icon:'spark',color:'blue',tags:['综合问答','信息整理','工作协同']},{id:'diagnosis',name:'设备诊断助手',desc:'整理设备异常现象，列出待确认信息，形成清晰的初步排查记录。',icon:'wrench',color:'blue',tags:['异常分析','信息采集','排查记录']},{id:'maintenance',name:'运维管理助手',desc:'辅助编写巡检模板、整理维护记录，让每一次运维工作都有迹可循。',icon:'clipboard',color:'teal',tags:['巡检清单','维护记录','交接整理']},{id:'solution',name:'方案咨询助手',desc:'梳理工况、接口与交付要求，为进一步的技术沟通准备需求清单。',icon:'layers',color:'purple',tags:['需求澄清','选型准备','客户沟通']}];
const docs=[{id:'diagnosis',title:'设备异常信息采集指引',category:'设备诊断',body:'<h3>01 · 先记录现象</h3><p>记录设备型号、报警代码、出现时间、持续时长，以及异常发生前后的工况变化。</p><h3>02 · 归集可用资料</h3><p>整理已有的温度、负载与环境记录，以及最近一次维护情况。只记录现场允许获取的信息。</p><h3>03 · 交由人员确认</h3><p>由具备资质的现场人员依据该型号手册确认后续检查项目。本示例不提供带电操作或设备控制指令。</p>'},{id:'maintenance',title:'日常巡检记录模板',category:'运维管理',body:'<h3>基础信息</h3><p>日期、班次、设备编号、位置、记录人。</p><h3>观察项目</h3><p>运行状态、报警信息、可见外观、环境条件、既有监测数据。</p><h3>异常闭环</h3><p>现象描述、发现时间、接收人、处理记录、复核状态。</p>'},{id:'solution',title:'项目选型需求采集清单',category:'方案咨询',body:'<h3>应用与工况</h3><p>应用场景、现有设备、负载特征、运行周期、安装环境。</p><h3>技术与协同</h3><p>供电条件、通讯协议、接口数量、尺寸约束、现场集成要求。</p><h3>交付要求</h3><p>预算范围、计划交期、验收项目、培训与售后需求。具体参数由双方技术人员确认。</p>'},{id:'mail',title:'客户技术沟通模板',category:'工作协同',body:'<h3>答复结构</h3><p>确认需求 → 复述已知信息 → 列出待补充资料 → 说明后续安排。</p><h3>使用原则</h3><p>未核实的参数不作确定承诺；未确认的时间使用待确认标记；发送前复核收件人及附件。</p>'}];
let sessions=[],active=null,expert='general',useKnowledge=true,busy=false,timer=null;
const getExpert=()=>experts.find(e=>e.id===expert);const current=()=>sessions.find(s=>s.id===active);
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');clearTimeout(timer);timer=setTimeout(()=>$('toast').classList.remove('show'),2400)}
function openModal(title,html){$('modal-title').textContent=title;$('modal-content').innerHTML=html;$('modal').showModal()}
function openDoc(id){const d=docs.find(d=>d.id===id);if(d)openModal(d.title,`<span class="demo-badge">演示文档 · ${esc(d.category)}</span>${d.body}<p class="answer-note">此文档为演示编写，不是实际产品技术资料。</p>`)}
function view(name){document.querySelectorAll('.view').forEach(e=>e.hidden=e.id!==name+'-view');document.querySelectorAll('.nav-item').forEach(e=>e.classList.toggle('active',e.dataset.view===name));$('page-name').textContent={chat:'AI 工作台',experts:'专家助手',knowledge:'知识库'}[name];$('sidebar').classList.remove('open')}
function updateHistory(){$('history').innerHTML=sessions.length?sessions.map(s=>`<button data-session="${s.id}" class="${active===s.id?'active':''}" title="${esc(s.title)}">${esc(s.title)}</button>`).join(''):'<div class="history-empty">开始一次对话，<br>让问题有迹可循。</div>'}
function newChat(id=expert){if(busy){toast('请等待当前演示回答完成');return}active=null;expert=id;$('current-expert').textContent=getExpert().name;$('messages').innerHTML='';$('welcome').hidden=false;$('prompt').value='';$('send').disabled=true;view('chat');updateHistory();$('prompt').focus()}
function chooseExpert(id){newChat(id);if($('modal').open)$('modal').close()}
function renderExperts(){$('expert-grid').innerHTML=experts.map(e=>`<article class="expert-card"><div class="expert-card-top"><span class="card-icon ${e.color}">${svg(e.icon)}</span><div><h2>${e.name}</h2><small>创安睿控 · 演示助手</small></div></div><p>${e.desc}</p><div class="tags">${e.tags.map(t=>`<span>${t}</span>`).join('')}</div><button data-expert="${e.id}">开始对话 <span>↗</span></button></article>`).join('');$('document-list').innerHTML=docs.map(d=>`<button class="document-row" data-doc="${d.id}"><span class="doc-icon">${svg('file')}</span><span><strong>${d.title}</strong><small>${d.category} &nbsp; / &nbsp; 示例文档 &nbsp; / &nbsp; V1.0</small></span><span class="doc-arrow">↗</span></button>`).join('')}
function replyFor(q){if(/演示|功能|介绍|你好|您好/.test(q))return{title:'欢迎来到创安睿控 AI 工作台',html:'<p>你可以在这里体验三条操作路径：</p><ol><li><strong>提出问题：</strong>点击首页示例，或在下方输入框直接提问。</li><li><strong>切换助手：</strong>进入专家助手，选择设备诊断、运维管理或方案咨询角色。</li><li><strong>追溯来源：</strong>点击回答下方的知识来源，查看对应的示例文档。</li></ol><p>当前为交互原型：回答来自预设内容，不会调用真实模型，也不会连接或控制设备。</p>',docs:[]};
if(/巡检|维护|保养|运维|交接/.test(q))return{title:'日常巡检记录 · 示例模板',html:'<p>可以先使用下面这份记录结构，再按设备手册和现场制度补充项目。</p><table><thead><tr><th>记录项目</th><th>填写内容</th><th>状态</th></tr></thead><tbody><tr><td>基础信息</td><td>日期、班次、设备编号、记录人</td><td>待填写</td></tr><tr><td>运行观察</td><td>运行状态、报警信息与异常现象</td><td>待确认</td></tr><tr><td>既有数据</td><td>现场允许读取的监测记录</td><td>待确认</td></tr><tr><td>异常交接</td><td>接收人、处理记录、复核状态</td><td>待填写</td></tr></tbody></table><p><strong>记录建议：</strong>将“发现的现象”与“确认的原因”分开填写，便于后续追溯。</p>',docs:['maintenance']};
if(/选型|方案|需求|客户.*确认|参数/.test(q))return{title:'先明确需求，再进入选型',html:'<p>可以从四个方面向客户补充信息：</p><ol><li><strong>应用场景：</strong>设备用途、负载特征、运行周期与目前遇到的问题。</li><li><strong>现场条件：</strong>已有设备、供电与安装条件、环境和空间约束。</li><li><strong>连接要求：</strong>通讯协议、接口需求，以及需要对接的系统。</li><li><strong>交付预期：</strong>预算、时间、验收条件与支持范围。</li></ol><p>收到这些信息后，可形成需求确认表。这个演示版不提供未经核实的产品型号或参数。</p>',docs:['solution']};
if(/邮件|答复|沟通/.test(q))return{title:'客户技术答复 · 草稿',html:'<p><strong>主题：</strong>关于［项目名称］的技术需求确认</p><p>您好：</p><p>感谢您提供项目情况。为便于进一步评估方案，烦请补充设备型号、应用场景、现场条件，以及希望解决的主要问题。</p><p>我们将基于确认后的资料，整理技术建议与待验证项目，并与您沟通下一步安排。</p><p>感谢配合。<br>［联系人 / 团队］</p><p class="answer-note">此为模板草稿；未发送任何邮件。</p>',docs:['mail']};
if(/报警|故障|过温|异常|诊断|温度/.test(q))return{title:'先收集信息，建立初步排查记录',html:'<p>仅凭现象还不能判断故障原因。建议先整理以下信息，供现场技术人员核实：</p><ol><li><strong>确认报警：</strong>记录设备型号、完整报警代码及出现时间。</li><li><strong>还原工况：</strong>整理报警前后的运行状态、负载变化和环境记录。</li><li><strong>核对维护：</strong>查看近期维护记录及同类异常是否重复出现。</li><li><strong>形成交接：</strong>将现象、已有数据与待确认项目交给具备资质的现场人员。</li></ol><p>具体检查与处理应依据对应设备手册及现场安全流程执行。</p><p><strong>还需要补充：</strong>设备型号和报警代码是什么？</p>',docs:['diagnosis']};
return{title:'已收到你的问题',html:`<p>你提出的是：“${esc(q)}”</p><p>当前为预设内容驱动的演示版，还不能针对任意问题进行真实推理。你可以继续体验以下示例：</p><ul><li>设备过温报警，如何整理排查信息？</li><li>生成设备日常巡检记录模板。</li><li>整理设备选型前的需求清单。</li><li>起草客户技术答复邮件。</li></ul>`,docs:[]}}
function answerHTML(m){return `<div class="assistant-heading"><span class="mini-mark">睿</span>${esc(m.expert)}<span class="demo-badge">模拟回答</span></div><div class="answer"><h3>${m.reply.title}</h3>${m.reply.html}${m.knowledge&&m.reply.docs.length?`<div class="sources">${m.reply.docs.map(id=>`<button class="source" data-doc="${id}">↗ ${docs.find(d=>d.id===id).title} · 示例</button>`).join('')}</div>`:''}<div class="message-actions"><button data-copy="${m.id}">${svg('copy')}复制</button><button data-like="${m.id}" class="${m.liked?'chosen':''}" aria-pressed="${!!m.liked}">${svg('like')}${m.liked?'已反馈':'有帮助'}</button></div></div>`}
function renderMessages(){const s=current();$('welcome').hidden=!!s?.messages.length;$('messages').innerHTML=s?s.messages.map(m=>`<article class="message ${m.role}">${m.role==='user'?`<div class="user-bubble">${esc(m.text)}</div>`:answerHTML(m)}</article>`).join(''):'';updateHistory()}
function scrollBottom(){$('conversation').scrollTop=$('conversation').scrollHeight}
async function send(text){const q=(text??$('prompt').value).trim();if(!q||busy)return;if(q.length>3000){toast('问题请控制在 3000 字以内');return}view('chat');busy=true;$('send').disabled=true;$('prompt').value='';if(!active){active=String(Date.now());sessions.unshift({id:active,title:q,expert,messages:[]})}const s=current();s.messages.push({id:Date.now()+'u',role:'user',text:q});renderMessages();const pending=document.createElement('article');pending.className='message assistant';pending.innerHTML=`<div class="assistant-heading"><span class="mini-mark">睿</span>${getExpert().name}<span class="demo-badge">模拟回答</span></div><div class="answer"><div class="typing" aria-label="正在整理演示回答"><span></span><span></span><span></span></div></div>`;$('messages').append(pending);scrollBottom();await new Promise(r=>setTimeout(r,650));s.messages.push({id:Date.now()+'a',role:'assistant',expert:getExpert().name,reply:replyFor(q),knowledge:useKnowledge});busy=false;renderMessages();scrollBottom();$('send').disabled=!$('prompt').value.trim()}
document.addEventListener('click',async e=>{const t=e.target.closest('button');if(!t)return;if(t.dataset.view)view(t.dataset.view);if(t.dataset.prompt)send(t.dataset.prompt);if(t.dataset.expert)chooseExpert(t.dataset.expert);if(t.dataset.doc)openDoc(t.dataset.doc);if(t.dataset.session){if(busy){toast('请等待当前回答完成');return}active=t.dataset.session;expert=current().expert;$('current-expert').textContent=getExpert().name;view('chat');renderMessages();scrollBottom()}if(t.dataset.like){const m=current().messages.find(m=>m.id===t.dataset.like);m.liked=!m.liked;renderMessages();toast(m.liked?'已记录本次演示反馈':'已取消反馈')}if(t.dataset.copy){const m=current().messages.find(m=>m.id===t.dataset.copy);const el=document.createElement('div');el.innerHTML=`${m.reply.title}\n${m.reply.html}`;try{await navigator.clipboard.writeText(el.innerText||el.textContent);toast('回答已复制')}catch{openModal('复制回答',`<textarea readonly rows="10" aria-label="回答内容">${esc(el.innerText||el.textContent)}</textarea>`)}}});
$('send').onclick=()=>send();$('prompt').oninput=()=>$('send').disabled=busy||!$('prompt').value.trim();$('prompt').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();send()}};$('new-chat').onclick=()=>newChat();document.querySelector('.brand').onclick=e=>{e.preventDefault();newChat('general')};$('menu').onclick=()=>$('sidebar').classList.toggle('open');document.querySelector('.main-shell').addEventListener('click',e=>{if(!e.target.closest('#menu'))$('sidebar').classList.remove('open')});$('close-modal').onclick=()=>$('modal').close();$('modal').onclick=e=>{if(e.target===$('modal')){const r=$('modal').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('modal').close()}};$('knowledge-toggle').onclick=()=>{useKnowledge=!useKnowledge;$('knowledge-toggle').classList.toggle('selected',useKnowledge);$('knowledge-toggle').setAttribute('aria-pressed',String(useKnowledge));toast(useKnowledge?'已开启示例来源展示':'已关闭示例来源展示')};$('expert-select').onclick=()=>openModal('选择专家助手',experts.map(e=>`<button class="modal-option" data-expert="${e.id}">${svg(e.icon)}<span>${e.name}<small>${e.tags.join(' · ')}</small></span></button>`).join(''));$('info').onclick=()=>openModal('关于这个演示版','<p><strong>创安睿控 AI 智能体</strong>是一个可交互的网页原型。</p><p>可体验：发送问题、查看模拟回答、切换专家、浏览示例知识、复制回答和切换本次页面内的对话记录。</p><p>当前未接入真实大模型、企业数据库或设备。所有知识条目均为演示编写；对话仅保留在当前页面内，刷新后清空。</p>');renderExperts();
if(document.modelContext?.registerTool){const lifecycle=new AbortController();const definitions=[{name:'send_demo_question',title:'向睿控演示助手提问',description:'发送问题并在当前聊天中生成预设的模拟回答，不调用真实模型。',inputSchema:{type:'object',properties:{question:{type:'string',minLength:1,maxLength:3000}},required:['question'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},async execute(input){if(!input||typeof input.question!=='string'||!input.question.trim()||input.question.length>3000)throw new Error('请输入 1 至 3000 字的问题');if(busy)throw new Error('当前回答尚未完成');await send(input.question);return{mode:'demo',title:current().messages.at(-1).reply.title,messageCount:current().messages.length}}},{name:'start_expert_conversation',title:'开启专家对话',description:'选择演示专家并开启空白对话；已有对话保留在本次页面记录中。',inputSchema:{type:'object',properties:{expertId:{type:'string',enum:experts.map(e=>e.id)}},required:['expertId'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||!experts.some(e=>e.id===input.expertId))throw new Error('助手不存在');if(busy)throw new Error('当前回答尚未完成');chooseExpert(input.expertId);return{expert:getExpert().name,status:'ready'}}}];for(const tool of definitions){try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{})}catch{}}window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true})}
